### ISSUE TITLE
Clicking on buttons will open the history card.

### ISSUE THREAD

**Issue by luca-angemi** [c727/home-assistant-tiles#11]
# Incomplete issues will be ignored
- [X] I have read README.md
- [X]  I have deleted my browser cache after updating tiles

**Description of problem:**
```
When clicking on a button the history card of the group pops up.
```

**Expected:**
```
No card should open.
```

**Tiles version:**
```
latest
```

**Affected browser:**
```
Chrome
```

**Home Assistant version:**
```
63.3
```

**Home Assistant `frontend:` config:**
```yaml
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles.html
```

**Home Assistant `customize:` config:**
```yaml
script.camera_button:
  custom_ui_state_card: state-card-tiles
  config:
    columns: 3
    column_width: 57px
    gap: 4px
    row_height: 57px
    entities:
    - entity: script.camera_up
      icon: mdi:arrow-up-thick
      column: 2
    - entity: script.camera_left
      icon: mdi:arrow-left-thick
      column: 1
    - entity: script.camera_down
      icon: mdi:arrow-down-thick
      column: 2
    - entity: script.camera_right
      icon: mdi:arrow-right-thick
      column: 3
```

**Error log from browser dev console - NOT from HA:**
```
N/A
```

**Screenshot:**
After click on any button

![image](https://user-images.githubusercontent.com/9977955/36816744-100ce78e-1cdf-11e8-960b-1aaf8a21907d.png)

**Comment by c727** [comment]
This was fixed today for dummy domain with more-info-card

**Comment by luca-angemi** [comment]
Hi,

I used your fix but the issue still persists. Do I have to change only the 2 html files, right?

**Comment by c727** [comment]
Yes, and clear cache after every update

**Comment by luca-angemi** [comment]
thanks for your answer. That's what I did: I changed the two html files, cleared the cache, restarted HA, but the issue still persists.

![image](https://user-images.githubusercontent.com/9977955/36828618-338d2872-1d1b-11e8-9866-280903a3daac.png)

**Comment by c727** [comment]
you don't have to restart HA if you update files in www btw

I tested once again and it's fixed in latest version...
you can also use a domain without more-info-card, like input_text, to avoid this

**Comment by luca-angemi** [comment]
thanks, I'll try input_text!
